### ISSUE TITLE
after entering something other than R/P/Q/L/<enter> when looking at a single post, <enter> is not recognized

### ISSUE THREAD

**Issue by bwo** [caraesten/ATty#1]
After the "choose an option" selection, if you select `1: Home Timeline`, you might _think_ that you can, when viewing a single post, select `2: Notifications Timeline` by entering `2<RET>`. However, you can't, which may or may not be a bug. But once you enter that unrecognized input, it *also* stops recognizing enter as meaning "go to the next post":

```
Choose an option (or X to quit):
1: Home Timeline, 
2: Notifications Timeline, 
3: Create Post
>1

 tef (tef.bsky.social) 
[tef's post goes here]

 [[R]eply Re[P]ost [Q]uote [L]ike] 
2

 [[R]eply Re[P]ost [Q]uote [L]ike] 
2

 [[R]eply Re[P]ost [Q]uote [L]ike] 


 [[R]eply Re[P]ost [Q]uote [L]ike] 
1

 [[R]eply Re[P]ost [Q]uote [L]ike] 
2

 [[R]eply Re[P]ost [Q]uote [L]ike] 


 [[R]eply Re[P]ost [Q]uote [L]ike] 


 [[R]eply Re[P]ost [Q]uote [L]ike] 


 [[R]eply Re[P]ost [Q]uote [L]ike] 
3

 [[R]eply Re[P]ost [Q]uote [L]ike] 


 [[R]eply Re[P]ost [Q]uote [L]ike] 
how to quit ed             

 [[R]eply Re[P]ost [Q]uote [L]ike] 
l

 [Liked] 

<next post is shown>
```

**Comment by caraesten** [comment]
oh huh! I'll take a look at this tomorrow morning and get a fix out ASAP after that, thank you for the report!

**Comment by bwo** [comment]
ah I'm guessing the issues is [here](https://github.com/caraesten/ATty/blob/main/src/main/kotlin/com/atty/scopes/PostScope.kt#L40-L44): *entering* the loop is guarded by the possibility of an empty string, but once we're *in* the loop it has to be one of `[rRpPqQlL]` exactly

**Comment by caraesten** [comment]
Fixed!
